services:
  terminal:
    image: terminal:1.0
    build: .
    container_name: Terminal
#    ports:
#      - 3000:3000
    volumes:
      - ./app/server.js:/app/server.js:ro
      - ./app/public:/app/public:ro
      - ./app/omz:/app/omz
    environment:
      - HOME_DIR=/mnt/SSD/docker
    pid: "host"
    privileged: true
    restart: always
networks:
  default:
    name: nginx_default
    external: true
